#include <stdint.h>
#pragma once

enum bootstage : uint8_t {
    BOOTSTAGE_EARLY_FB = 0,
    BOOTSTAGE_EARLY_MP = 1,
    BOOTSTAGE_EARLY_ALLOCATORS = 2,
    BOOTSTAGE_EARLY_DEVICES = 3,
    BOOTSTAGE_MID_SCHEDULER = 4,
    BOOTSTAGE_MID_MP = 5,
    BOOTSTAGE_LATE_DEVICES = 6,
    BOOTSTAGE_COMPLETE = 7,
};
