#include "internal.h"

/* BG and MAX both have unlimited scans. This is because they
 * are never called from kmalloc/kfree, and we can dilly dally
 * a bit due to the absence of a need for speed. */
#define SLAB_GC_AGG_BG_SCAN_MAX SIZE_MAX
#define SLAB_GC_AGG_RECLAIM_SCAN_MAX 32
#define SLAB_GC_AGG_STANDARD_SCAN_MAX 64
#define SLAB_GC_AGG_LOW_MEM_SCAN_MAX 1024
#define SLAB_GC_AGG_EMERGENCY_SCAN_MAX 4096
#define SLAB_GC_AGG_MAX_SCAN_MAX SIZE_MAX
static const size_t gc_agg_scan_max[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_SCAN_MAX,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_SCAN_MAX,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_SCAN_MAX,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_SCAN_MAX,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_SCAN_MAX,
};

/* BG and MAX once again are allowed to scan everything because
 * they are always executed from contexts where they can dawdle for days */
#define SLAB_GC_AGG_BG_SCAN_PCT 100
#define SLAB_GC_AGG_RECLAIM_SCAN_PCT 2
#define SLAB_GC_AGG_STANDARD_SCAN_PCT 5
#define SLAB_GC_AGG_LOW_MEM_SCAN_PCT 15
#define SLAB_GC_AGG_EMERGENCY_SCAN_PCT 25
#define SLAB_GC_AGG_MAX_SCAN_PCT 100
static const size_t gc_agg_scan_pct[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_SCAN_PCT,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_SCAN_PCT,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_SCAN_PCT,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_SCAN_PCT,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_SCAN_PCT,
};

#define SLAB_GC_AGG_BG_AGE_FACTOR_PCT 150
#define SLAB_GC_AGG_RECLAIM_AGE_FACTOR_PCT 100
#define SLAB_GC_AGG_STANDARD_AGE_FACTOR_PCT 125
#define SLAB_GC_AGG_LOW_MEM_AGE_FACTOR_PCT 150
#define SLAB_GC_AGG_EMERGENCY_AGE_FACTOR_PCT 200
#define SLAB_GC_AGG_MAX_AGE_FACTOR_PCT 300
static const size_t gc_agg_age_factor_pct[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_AGE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_AGE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_AGE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_AGE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_EMERGENCY] = SLAB_GC_AGG_EMERGENCY_AGE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_AGE_FACTOR_PCT,
};

#define SLAB_GC_AGG_BG_SIZE_FACTOR_PCT 100
#define SLAB_GC_AGG_RECLAIM_SIZE_FACTOR_PCT 200
#define SLAB_GC_AGG_STANDARD_SIZE_FACTOR_PCT 225
#define SLAB_GC_AGG_LOW_MEM_SIZE_FACTOR_PCT 200
#define SLAB_GC_AGG_EMERGENCY_SIZE_FACTOR_PCT 250
#define SLAB_GC_AGG_MAX_SIZE_FACTOR_PCT 300
static const size_t gc_agg_size_factor_pct[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_SIZE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_SIZE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_SIZE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_SIZE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_EMERGENCY] = SLAB_GC_AGG_EMERGENCY_SIZE_FACTOR_PCT,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_SIZE_FACTOR_PCT,
};

#define SLAB_GC_AGG_BG_RECYCLE_PENALTY_PCT 75
#define SLAB_GC_AGG_RECLAIM_RECYCLE_PENALTY_PCT 50
#define SLAB_GC_AGG_STANDARD_RECYCLE_PENALTY_PCT 50
#define SLAB_GC_AGG_LOW_MEM_RECYCLE_PENALTY_PCT 25
#define SLAB_GC_AGG_EMERGENCY_RECYCLE_PENALTY_PCT 0
#define SLAB_GC_AGG_MAX_RECYCLE_PENALTY_PCT 0
static const size_t gc_agg_recycle_penalty_pct[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_RECYCLE_PENALTY_PCT,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_RECYCLE_PENALTY_PCT,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_RECYCLE_PENALTY_PCT,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_RECYCLE_PENALTY_PCT,
    [SLAB_GC_FLAG_AGG_EMERGENCY] = SLAB_GC_AGG_EMERGENCY_RECYCLE_PENALTY_PCT,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_RECYCLE_PENALTY_PCT,
};

#define SLAB_GC_AGG_BG_MAX_UNFIT 1
#define SLAB_GC_AGG_RECLAIM_MAX_UNFIT 32
#define SLAB_GC_AGG_STANDARD_MAX_UNFIT 16
#define SLAB_GC_AGG_LOW_MEM_MAX_UNFIT 8
#define SLAB_GC_AGG_EMERGENCY_MAX_UNFIT 4
#define SLAB_GC_AGG_MAX_MAX_UNFIT 1
static const size_t gc_agg_max_unfit_slabs[SLAB_GC_FLAG_AGG_COUNT] = {
    [SLAB_GC_FLAG_AGG_BG] = SLAB_GC_AGG_BG_MAX_UNFIT,
    [SLAB_GC_FLAG_AGG_RECLAIM] = SLAB_GC_AGG_RECLAIM_MAX_UNFIT,
    [SLAB_GC_FLAG_AGG_STANDARD] = SLAB_GC_AGG_STANDARD_MAX_UNFIT,
    [SLAB_GC_FLAG_AGG_LOW_MEM] = SLAB_GC_AGG_LOW_MEM_MAX_UNFIT,
    [SLAB_GC_FLAG_AGG_EMERGENCY] = SLAB_GC_AGG_EMERGENCY_MAX_UNFIT,
    [SLAB_GC_FLAG_AGG_MAX] = SLAB_GC_AGG_MAX_MAX_UNFIT,
};
