[package]
name = "kernel_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
target = "x86_64-unknown-none"

[profile.release]
panic = "abort"
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]

