const char *large_test_string =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque "
    "gravida commodo enim et sagittis. Sed vehicula odio nec diam "
    "interdum, volutpat pellentesque nibh aliquet. Phasellus ex augue, "
    "tempor at augue in, suscipit ornare ante. Suspendisse ac lectus "
    "nulla. Suspendisse nunc sem, consequat ut odio et, commodo "
    "pellentesque sem. Etiam bibendum, dui ac placerat pulvinar, massa "
    "augue sagittis erat, at suscipit eros mi a massa. Maecenas dapibus "
    "nisi lacus, ut malesuada enim cursus vitae. Pellentesque habitant "
    "morbi tristique senectus et netus et malesuada fames ac turpis "
    "egestas. Maecenas lobortis eleifend placerat. Donec pretium sapien "
    "lacus, eu convallis tortor commodo non. Quisque sem enim, ultricies "
    "quis sodales eu, consectetur non nisi. Donec mollis nibh neque, eu "
    "elementum felis euismod vitae. Aliquam erat volutpat. Ut ut neque non "
    "ipsum gravida tristique. Orci varius natoque penatibus et magnis dis "
    "parturient montes, nascetur ridiculus mus. Aenean sollicitudin "
    "convallis odio vitae finibus."

    "Pellentesque lacus massa, venenatis id ultricies at, pharetra et leo. "
    "Morbi ultricies est id tellus consequat, id hendrerit elit euismod. "
    "Donec nec facilisis urna. Maecenas blandit commodo ex, vel lacinia "
    "diam lobortis at. In nec dignissim elit. Nunc odio augue, luctus a "
    "ante vitae, pulvinar lobortis neque. Proin eu metus urna. Fusce "
    "mauris neque, efficitur a lobortis at, egestas ut augue. Nunc arcu "
    "diam, laoreet sit amet mi sed, viverra blandit diam. Proin viverra "
    "ligula vel tortor fermentum, quis pharetra nisi imperdiet. Donec "
    "pellentesque, lorem nec laoreet ullamcorper, nibh ipsum vestibulum "
    "arcu, vitae iaculis sem erat nec est. Praesent porttitor, ipsum at "
    "blandit auctor, sapien enim rutrum nibh, eu condimentum elit quam "
    "quis lectus. Nullam a tortor a lorem pellentesque finibus in quis "
    "diam. Donec vitae justo felis."

    "Duis ultricies urna eget nulla scelerisque suscipit. Donec nec libero "
    "iaculis, lacinia quam ut, dictum lorem. Curabitur metus ligula, "
    "finibus eu suscipit in, gravida ac dui. Praesent nisl risus, iaculis "
    "sed justo eget, facilisis vehicula urna. Praesent ut efficitur est. "
    "Donec et tempor nulla, ut vehicula erat. Vivamus interdum sed dui ut "
    "vehicula. Sed mi diam, consectetur sed arcu at, lacinia porta ex. "
    "Etiam luctus blandit metus in porta. Ut sed volutpat tortor. Nam "
    "molestie et tortor ac posuere. Praesent a ullamcorper lacus. Donec "
    "efficitur lectus sed venenatis consequat. Curabitur lacinia nec ante "
    "a ultrices.";
