name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'kernel/**'
      - 'include/**'
  pull_request:
    paths:
      - 'kernel/**'
      - 'include/**'
  workflow_dispatch: # manual trigger
  workflow_run:
    workflows: ["Update CI Container"]
    types:
      - completed

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build (${{ matrix.compiler }} / ${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    container:
      image: ghcr.io/axvonx/charmos-x86-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_KEY }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install compiler toolchain
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            apt-get update && apt-get install -y clang lld llvm
          elif [ "${{ matrix.compiler }}" = "gcc" ] && [ "$(uname -m)" != "x86_64" ]; then
            apt-get update && apt-get install -y gcc-x86-64-linux-gnu binutils-x86-64-linux-gnu
          fi

      - name: Compile
        run: ./scripts/build.sh -t ${{ matrix.build_type }} --compiler ${{ matrix.compiler }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iso-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: build/charmos-x86_64.iso
          retention-days: 7

  all-features:
    name: All-Features build (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    container:
      image: ghcr.io/axvonx/charmos-x86-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_KEY }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install compiler toolchain
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            apt-get update && apt-get install -y clang lld llvm
          elif [ "${{ matrix.compiler }}" = "gcc" ] && [ "$(uname -m)" != "x86_64" ]; then
            apt-get update && apt-get install -y gcc-x86-64-linux-gnu binutils-x86-64-linux-gnu
          fi

      - name: Compile with all features, diagnostics, and tests enabled
        run: >
          ./scripts/build.sh -t Debug --compiler ${{ matrix.compiler }}
          --
          -DDEBUG_ALL=ON
          -DTEST_ALL=ON
          -DPROFILING_ALL=ON
          -DTEST_NIGHTMARE_ALL=ON
          -DINJECT_ALL=ON
