name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Dependencies
        run: sudo apt update -y && sudo apt install xorriso nasm qemu-system -y 

      - name: Compile 
        run:  ./build.sh

      - name: Run tests 
        run: |
          cd build
          export TERM=dumb

          for i in $(seq 1 10); do
            echo "[INFO] Test iteration $i/10"

            dd if=/dev/zero of=disk.img bs=10M count=1
            mkfs.ext2 -F disk.img

            set +e
            timeout 30s make tests | tee qemu.log
            EXIT_CODE=${PIPESTATUS[0]}
            echo "[INFO]: make tests exited with $EXIT_CODE"

            if grep -q "all tests pass" qemu.log; then
              echo "[PASS] Iteration $i passed!"
            else
              echo "[FAIL] Iteration $i failed:"
              tail -n 40 qemu.log
              exit 1
            fi
          done

