name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Dependencies
        run: sudo apt update -y && sudo apt install xorriso nasm qemu-system gdb -y 

      - name: Compile 
        run:  ./build.sh

      - name: Run tests 10 times with GDB on failure
        run: |
          cd build
          export TERM=dumb

          for i in $(seq 1 10); do
            echo "[INFO] Test iteration $i/10"

            dd if=/dev/zero of=disk.img bs=10M count=1
            mkfs.ext2 -F disk.img

            set +e
            make tests | tee qemu.log &

            sleep 30

            if grep -q "all tests pass" qemu.log; then
              echo "[PASS] Iteration $i passed!"
              pkill -f qemu-system-x86_64
            else
              echo "[FAIL] Iteration $i failed, collecting GDB backtrace..."
              gdb -ex "target remote localhost:1234" \
                   kernel/kernel \
                  -ex "set pagination off" \
                  -ex "info threads" \
                  -ex "thread apply all bt full" \
                  -ex "quit" || true
              tail -n 40 qemu.log
              pkill -f qemu-system-x86_64
              exit 1
            fi
          done
